import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { signIn } from "next-auth/react";
import { useContext } from "react";
import { AuthContext } from "../context/auth";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { isLoggedIn, logout } = useContext(AuthContext);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {isLoggedIn ? (
          <button onClick={logout}>Salir</button>
        ) : (
          <button
            onClick={() => {
              signIn();
            }}
          >
            Login
          </button>
        )}
      </main>
      <footer className={styles.footer}></footer>
    </>
  );
}
